services:
  web:
    build:
      context: ./CompanyKnowledgeWeb
      dockerfile: Dockerfile
    container_name: company-knowledge-web
    ports:
      - "4200:4200"
    depends_on:
      - api

  api:
    build:
      context: ./CompanyKnowledgeApi
      dockerfile: Dockerfile
    container_name: company-knowledge-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=company_knowledge;Username=company_knowledge;Password=company_knowledge_dev
      AI__OllamaBaseUrl: http://ollama:11434
      AI__EmbeddingModel: bge-m3
      AI__ExpectedDimensions: 1024
      AI__ChatModel: qwen2.5:1.5b
      AI__Temperature: 0.2
      AI__RequestTimeoutSeconds: 300
      AI__MaxOutputTokens: 256
      BackgroundJobs__WorkerCount: 1
      BackgroundJobs__EnableDashboard: true
    ports:
      - "8080:8080"
    volumes:
      - api_document_storage:/app/storage
    depends_on:
      - postgres
      - ollama

  postgres:
    image: pgvector/pgvector:pg18
    container_name: company-knowledge-postgres
    environment:
      POSTGRES_DB: company_knowledge
      POSTGRES_USER: company_knowledge
      POSTGRES_PASSWORD: company_knowledge_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  ollama:
    image: ollama/ollama:latest
    container_name: company-knowledge-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
  api_document_storage:
